/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.chromium.chrome;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static int autofill_dialog_footer_height=0x7f060016;
        /**  Autofill Dialog 
         */
        public static int autofill_dialog_max_height=0x7f060013;
        public static int autofill_dialog_title_height=0x7f060015;
        public static int autofill_dialog_vertical_margin=0x7f060014;
        public static int autofill_dialog_width=0x7f060012;
        /**  Autofill Dialog 
         */
        public static int autofill_edit_height=0x7f060003;
        public static int autofill_edit_margin=0x7f060004;
        public static int autofill_edit_text_size=0x7f060005;
        public static int autofill_field_icon_height=0x7f060006;
        public static int autofill_field_icon_width=0x7f060007;
        public static int autofill_menu_icon_height=0x7f060008;
        public static int autofill_menu_icon_width=0x7f060009;
        public static int autofill_menu_item_padding=0x7f06000a;
        public static int autofill_menu_item_size=0x7f06000b;
        public static int autofill_notification_padding=0x7f06000c;
        public static int autofill_notification_text_size=0x7f06000d;
        public static int autofill_spinner_offset=0x7f06000e;
        public static int autofill_steady_margin=0x7f06000f;
        public static int autofill_steady_text_size=0x7f060010;
        public static int autofill_translation_anim_distance=0x7f060011;
        /**  Certificate Viewer Dimensions 
         */
        public static int certificate_viewer_padding=0x7f060002;
        /** 
         14.5 = Seekbar thumb width - border width, but it depends on the width
	     of the seek bar icon.
    
         */
        public static int color_picker_gradient_margin=0x7f060000;
        /**  Link Preview dimensions 
         */
        public static int link_preview_overlay_radius=0x7f060001;
    }
    public static final class drawable {
        public static int arrow=0x7f020000;
        public static int autofill_popup_background=0x7f020001;
        public static int autofill_popup_background_down=0x7f020002;
        public static int autofill_popup_background_up=0x7f020003;
        public static int bubble=0x7f020004;
        public static int bubble_arrow_up=0x7f020005;
        public static int color_picker_advanced_select_handle=0x7f020006;
        public static int color_picker_border=0x7f020007;
        public static int controlled_setting_mandatory_large=0x7f020008;
        public static int divider_horizontal_bright=0x7f020009;
        public static int globe_favicon=0x7f02000a;
        public static int ic_menu_search_holo_light=0x7f02000b;
        public static int ic_menu_share_holo_light=0x7f02000c;
        public static int infobar_autofill=0x7f02000d;
        public static int infobar_autologin=0x7f02000e;
        public static int infobar_camera=0x7f02000f;
        public static int infobar_cookie=0x7f020010;
        public static int infobar_desktop_notifications=0x7f020011;
        public static int infobar_didyoumean=0x7f020012;
        public static int infobar_geolocation=0x7f020013;
        public static int infobar_incomplete=0x7f020014;
        public static int infobar_lock=0x7f020015;
        public static int infobar_microphone=0x7f020016;
        public static int infobar_multiple_downloads=0x7f020017;
        public static int infobar_plugin=0x7f020018;
        public static int infobar_plugin_crashed=0x7f020019;
        public static int infobar_questionmark=0x7f02001a;
        public static int infobar_restore=0x7f02001b;
        public static int infobar_savepassword=0x7f02001c;
        public static int infobar_theme=0x7f02001d;
        public static int infobar_translate=0x7f02001e;
        public static int infobar_waning=0x7f02001f;
        public static int infobar_warning=0x7f020020;
        public static int master_card=0x7f020021;
        public static int missing=0x7f020022;
        public static int ondemand_overlay=0x7f020023;
        public static int pageinfo_bad=0x7f020024;
        public static int pageinfo_good=0x7f020025;
        public static int pageinfo_info=0x7f020026;
        public static int pageinfo_warning_major=0x7f020027;
        public static int pageinfo_warning_minor=0x7f020028;
        public static int visa=0x7f020029;
        public static int wallet_logo=0x7f02002a;
    }
    public static final class id {
        public static int accounts_logo=0x7f080007;
        public static int accounts_spinner=0x7f080008;
        public static int adapter_item_edit_button=0x7f08003b;
        public static int adapter_item_line_1=0x7f080039;
        public static int adapter_item_line_2=0x7f08003a;
        public static int address_spinner=0x7f08002f;
        public static int arrow_image=0x7f080054;
        public static int autofill_editing_spinner_item=0x7f080024;
        public static int autofill_label=0x7f08003d;
        public static int autofill_menu_item=0x7f080036;
        public static int autofill_menu_text=0x7f080037;
        /**  AutofillPopup constants 
         */
        public static int autofill_popup_window=0x7f080000;
        public static int autofill_sublabel=0x7f08003e;
        public static int billing_city=0x7f080014;
        public static int billing_country_spinner=0x7f080017;
        public static int billing_label=0x7f08002c;
        public static int billing_phone_number=0x7f080018;
        public static int billing_spinner=0x7f08002d;
        public static int billing_state=0x7f080015;
        public static int billing_street_address_1=0x7f080012;
        public static int billing_street_address_2=0x7f080013;
        public static int billing_zip_code=0x7f080016;
        public static int bottom_notifications=0x7f080033;
        public static int card_number=0x7f08000c;
        public static int cardholder_name=0x7f080010;
        public static int cc_billing_label=0x7f080028;
        public static int cc_billing_spinner=0x7f080029;
        public static int cc_icon=0x7f080038;
        public static int cc_label=0x7f08002a;
        public static int cc_spinner=0x7f08002b;
        public static int color_picker_advanced=0x7f080043;
        public static int color_picker_simple=0x7f080045;
        public static int color_picker_simple_border=0x7f080044;
        public static int content=0x7f080001;
        public static int cvc_challenge=0x7f08003c;
        public static int cvc_code=0x7f08000f;
        public static int date_picker=0x7f08004a;
        public static int editing_layout_billing=0x7f080011;
        public static int editing_layout_cc_billing=0x7f08000a;
        public static int editing_layout_credit_card=0x7f08000b;
        public static int editing_layout_email=0x7f080019;
        public static int editing_layout_shipping=0x7f08001b;
        public static int email_address=0x7f08001a;
        public static int email_label=0x7f080030;
        public static int email_spinner=0x7f080031;
        public static int expiration_month_spinner=0x7f08000d;
        public static int expiration_year_spinner=0x7f08000e;
        public static int footer=0x7f080003;
        public static int general_layout=0x7f080025;
        public static int gradient=0x7f080041;
        public static int gradient_border=0x7f080040;
        public static int icon_view=0x7f080052;
        public static int js_modal_dialog_prompt=0x7f08004c;
        public static int line_bottom=0x7f080034;
        public static int line_top=0x7f080009;
        public static int loading_icon=0x7f080002;
        public static int main_text=0x7f080055;
        public static int more_colors_button=0x7f080047;
        public static int more_colors_button_border=0x7f080046;
        public static int negative_button=0x7f080004;
        public static int pickers=0x7f08004e;
        public static int position_in_year=0x7f08004f;
        public static int positive_button=0x7f080005;
        public static int recipient_name=0x7f08001c;
        public static int save_locally_checkbox=0x7f080032;
        public static int seek_bar=0x7f080042;
        public static int selected_color_view=0x7f080049;
        public static int selected_color_view_border=0x7f080048;
        public static int shipping_city=0x7f08001f;
        public static int shipping_country_spinner=0x7f080022;
        public static int shipping_label=0x7f08002e;
        public static int shipping_phone_number=0x7f080023;
        public static int shipping_state=0x7f080020;
        public static int shipping_street_address_1=0x7f08001d;
        public static int shipping_street_address_2=0x7f08001e;
        public static int shipping_zip_code=0x7f080021;
        public static int sub_text=0x7f080056;
        public static int suppress_js_modal_dialogs=0x7f08004d;
        public static int terms_info=0x7f080035;
        public static int text=0x7f08003f;
        public static int text_wrapper=0x7f080053;
        public static int time_picker=0x7f08004b;
        public static int title=0x7f080006;
        public static int top_checkbox_notification=0x7f080026;
        public static int top_notifications=0x7f080027;
        public static int top_view=0x7f080051;
        public static int website_settings_description=0x7f080059;
        public static int website_settings_headline=0x7f080058;
        public static int website_settings_icon=0x7f080057;
        public static int year=0x7f080050;
    }
    public static final class layout {
        public static int autofill_dialog_content=0x7f040000;
        public static int autofill_dialog_title=0x7f040001;
        public static int autofill_editing_layout_credit_card=0x7f040002;
        public static int autofill_editing_layout_email=0x7f040003;
        public static int autofill_editing_layout_shipping=0x7f040004;
        public static int autofill_editing_spinner_item=0x7f040005;
        public static int autofill_general_layout=0x7f040006;
        public static int autofill_menu_item=0x7f040007;
        public static int autofill_simple_menu_item=0x7f040008;
        public static int autofill_text=0x7f040009;
        public static int color_picker_advanced_component=0x7f04000a;
        public static int color_picker_dialog_content=0x7f04000b;
        public static int color_picker_dialog_title=0x7f04000c;
        public static int date_time_picker_dialog=0x7f04000d;
        public static int js_modal_dialog=0x7f04000e;
        public static int two_field_date_picker=0x7f04000f;
        public static int validation_message_bubble=0x7f040010;
        public static int website_settings=0x7f040011;
    }
    public static final class mipmap {
        public static int app_icon=0x7f030000;
        public static int bookmark_widget_bg=0x7f030001;
        public static int bookmark_widget_bg_highlights=0x7f030002;
    }
    public static final class string {
        public static int accessibility_content_view=0x7f05000b;
        public static int accessibility_date_picker_month=0x7f050014;
        public static int accessibility_date_picker_week=0x7f050015;
        public static int accessibility_date_picker_year=0x7f050016;
        public static int accessibility_datetime_picker_date=0x7f050012;
        public static int accessibility_datetime_picker_time=0x7f050013;
        public static int accessibility_js_modal_dialog_prompt=0x7f050023;
        public static int actionbar_share=0x7f050009;
        public static int actionbar_web_search=0x7f05000a;
        public static int autofill_add_button=0x7f05002c;
        public static int autofill_edit_button=0x7f05002d;
        public static int autofill_fetch_message=0x7f05002f;
        public static int autofill_negative_button_editing=0x7f05002b;
        public static int autofill_positive_button_editing=0x7f05002a;
        public static int autofill_terms_of_service=0x7f05002e;
        public static int certtitle=0x7f050024;
        public static int color_picker_button_cancel=0x7f050007;
        public static int color_picker_button_more=0x7f050002;
        public static int color_picker_button_set=0x7f050006;
        public static int color_picker_dialog_title=0x7f050008;
        public static int color_picker_hue=0x7f050003;
        public static int color_picker_saturation=0x7f050004;
        public static int color_picker_value=0x7f050005;
        public static int date_picker_dialog_clear=0x7f05000d;
        public static int date_picker_dialog_set=0x7f05000c;
        public static int date_picker_dialog_title=0x7f05000e;
        public static int date_time_picker_dialog_title=0x7f05000f;
        public static int dont_reload_this_page=0x7f05001f;
        public static int firstrun_signed_in_description=0x7f050031;
        public static int firstrun_signed_in_title=0x7f050030;
        public static int js_modal_dialog_cancel=0x7f050021;
        public static int js_modal_dialog_confirm=0x7f050020;
        public static int leave_this_page=0x7f05001c;
        public static int low_memory_error=0x7f050000;
        public static int media_player_error_button=0x7f05001a;
        public static int media_player_error_text_invalid_progressive_playback=0x7f050018;
        public static int media_player_error_text_unknown=0x7f050019;
        public static int media_player_error_title=0x7f050017;
        public static int media_player_loading_video=0x7f05001b;
        public static int month_picker_dialog_title=0x7f050010;
        public static int opening_file_error=0x7f050001;
        public static int reload_this_page=0x7f05001e;
        public static int sad_tab_help_link=0x7f050035;
        public static int sad_tab_help_message=0x7f050034;
        public static int sad_tab_message=0x7f050033;
        public static int sad_tab_reload_label=0x7f050036;
        public static int sad_tab_title=0x7f050032;
        public static int stay_on_this_page=0x7f05001d;
        public static int suppress_js_modal_dialogs=0x7f050022;
        public static int sync_error_connection=0x7f050027;
        public static int sync_error_domain=0x7f050028;
        public static int sync_error_ga=0x7f050026;
        public static int sync_error_generic=0x7f050025;
        public static int sync_error_service_unavailable=0x7f050029;
        public static int week_picker_dialog_title=0x7f050011;
    }
    public static final class style {
        public static int AutofillPopupWindow=0x7f070000;
    }
}
